version: '3'
services:
  ondevamos-db:
    container_name: ondevamos-db
    image: postgres:alpine
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    volumes:
      - ondevamos-db:/var/lib/postgresql/data
    networks:
      - ondevamos-api
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:5432'

  ondevamos-adminer:
    container_name: ondevamos-adminer
    image: adminer
    restart: unless-stopped
    ports:
      - '9090:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=ondevamos-db
    networks:
      - ondevamos-api
    depends_on:
      - ondevamos-db

volumes:
  ondevamos-db:

networks:
  ondevamos-api:
