version: '3'

networks:
  traefik_public:
    external: true

services:
  ondevamos-api:
    container_name: ondevamos-api
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: ondevamos-api:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ondevamos-db
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./pnpm-lock.json:/opt/pnpm-lock.json

      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    networks:
      - traefik_public
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_public
      - traefik.http.routers.ondevamos-api.rule=Host(`api.ondevamos.app`)
      - traefik.http.routers.ondevamos-api.entrypoints=websecure
      - traefik.http.routers.ondevamos-api.tls=true
      - traefik.http.routers.bitwarden-ui.service=ondevamos-api
      - traefik.http.routers.ondevamos-api.middlewares=secure-headers@file,cloudflare-ipwhitelist@file,real-ip@file
      - traefik.http.services.ondevamos-api.loadbalancer.server.port=1337
